version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GOARM=5
    gcflags:
      - -trimpath
    ldflags:
      - -s 
      - -w 
      - -X github.com/qbee-io/qbee-agent/app.Version={{.Version}}
      - -X github.com/qbee-io/qbee-agent/app.Commit={{.FullCommit}}
    targets:
      - linux_amd64
      - linux_386
      - linux_arm
      - linux_arm64
      - linux_loong64
      - linux_mips
      - linux_mips64
      - linux_mips64le
      - linux_mipsle
      - linux_ppc64
      - linux_ppc64le
      - linux_riscv64
      - linux_s390x

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - vendor: qbee.io
    homepage: https://qbee.io/
    maintainer: The Qbee Team <support@qbee.io>

    description: |-
      Qbee agent
      Qbee is a lightweight system management platform for IoT devices.
    license: Apache 2.0

    file_name_template: "{{.ConventionalFileName }}"

    priority: extra
    section: default 

    formats:
      - deb
      - rpm
    
    contents:
      - src: package/share/
        dst: /opt/qbee/share/
        type: tree
        file_info:
          mode: 0600
          owner: root
          group: root
      
      - src: package/bin/
        dst: /opt/qbee/bin
        type: tree
        file_info:
          mode: 0755
          owner: root
          group: root
      
      - src: package/init-scripts/systemd/
        dst: /lib/systemd/system/
        type: tree
        file_info:
          mode: 0644
          owner: root
          group: root

    scripts:
      preinstall: package/install-scripts/preinst
      postinstall: package/install-scripts/postinst
      preremove: package/install-scripts/prerm
    
    overrides:
      rpm:
        scripts:
          preremove: package/install-scripts/prerm-rpm
      deb: 
        scripts:
          preremove: package/install-scripts/prerm-deb
