FROM golang:1.25.3 as builder

ARG version
ENV VERSION_VAR=go.qbee.io/agent/app.Version

ENV CGO_ENABLED=0

WORKDIR /src

COPY . /src

# build the agent
RUN --mount=type=cache,target=/go \
    --mount=type=cache,target=/root/.cache/go-build \
    go build \
    -ldflags "-s -w -X ${VERSION_VAR}=$version" \
    -o /usr/bin/qbee-agent \
    main.go

FROM registry.access.redhat.com/ubi9/ubi:latest

COPY test/resources/rhel /yum-repo

COPY <<EOF /etc/yum.repos.d/qbee.repo
[qbee-dev]
name=qbee-dev
baseurl=file:///yum-repo/repo
enabled=1
gpgcheck=0
EOF

RUN mkdir /etc/qbee && echo '{}' > /etc/qbee/qbee-agent.json
COPY --from=builder /usr/bin/qbee-agent /usr/bin/qbee-agent

WORKDIR /app

RUN yum install -y sudo
RUN adduser --system --home-dir /var/lib/qbee-agent --create-home --shell /usr/sbin/nologin qbee-agent
COPY package/share/sudoers/99-qbee-agent /etc/sudoers.d/99-qbee-agent

CMD [ "/bin/sh" ]

