#!/bin/sh

### BEGIN INIT INFO
# Provides:          qbee-agent
# Required-Start:    $network
# Should-Start:
# Required-Stop:     $network
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: qbee.io fleet management agent
### END INIT INFO

pidfile=/var/run/qbee-agent.pid
launcher=/usr/bin/qbee-agent

start_qbee_agent()
{
    echo "Starting qbee-agent"
    start-stop-daemon -q -S -m -p $pidfile -b -x $launcher -- start
}

stop_qbee_agent()
{
    echo "Stopping qbee-agent"
    start-stop-daemon -q -K -p $pidfile -s INT
    rm $pidfile -f
}

die()
{
    exit 1
}

case "$1" in
  start)
        start_qbee_agent
        ;;
  stop)
        stop_qbee_agent
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        if [ -f $pidfile ]; then
            echo "qbee-agent (pid $(cat $pidfile)) is running..."
            exit 0
        else
            echo "qbee-agent is stopped"
        fi
        exit 3
        ;;
  *)
        echo "Usage: qbee-agent { start | stop | restart | status }" >&2
        exit 1
        ;;
esac

exit 0
